# Generated by Django 6.1 on 2026-08-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_moodboardimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodboardimage",
            name="unsplash_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
