# Generated by Django 6.1 on 2026-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_moodboardimage_unsplash_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="moodboardimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unsplash_id__isnull", False)),
                fields=("moodboard", "unsplash_id"),
                name="unique_unsplash_image_per_moodboard",
            ),
        ),
    ]
